import type {
  TrainingScenarioDefinition,
  TrainingScenarioWorkflowAction,
  TrainingScenarioWorkflowDefinition,
} from './types'

export const idleTrainingScenarioDefinition: TrainingScenarioDefinition = {
  defaultTargetTrainId: '317',
  duration: '00:00',
  id: 'idle',
  incident: 'None',
  kind: 'DOOR_FAULT',
  objective: 'Select Launch, Withdraw, or Door Fault to arm a training scenario.',
  target: 'No active scenario',
  title: 'Idle',
  tasks: [],
}

export const trainingScenarioDefinitions: readonly TrainingScenarioDefinition[] = [
  {
    defaultTargetTrainId: '306',
    duration: '06:00',
    id: 'train-launch',
    incident: 'Train launch',
    kind: 'TRAIN_LAUNCH',
    objective: 'Launch a train from the RT depot into live mainline service while timetable traffic continues.',
    target: 'RT1 / RT2 launch to SKG timetable service',
    title: 'Train Launch',
    tasks: [
      {
        id: 'select-launch-train',
        label: 'Select train to launch',
        mappedTaskId: 'selectTrain',
        monitor: 'Monitor 03 Timetable',
        weight: 15,
      },
      {
        critical: true,
        evidenceKeywords: ['route', 'launch'],
        id: 'set-launch-route',
        label: 'Set launch route from depot to SKG',
        mappedTaskId: 'setRoute',
        monitor: 'Line Map',
        weight: 30,
      },
      {
        evidenceKeywords: ['dispatch', 'departure'],
        id: 'dispatch-launch-train',
        label: 'Dispatch launch train',
        mappedTaskId: 'dispatchTrain',
        monitor: 'Line Map',
        weight: 35,
      },
      {
        id: 'review-launch-outcome',
        label: 'Review final launch state',
        mappedTaskId: 'completeScenario',
        monitor: 'IOS',
        weight: 20,
      },
    ],
  },
  {
    defaultTargetTrainId: '312',
    duration: '07:00',
    id: 'train-withdrawal',
    incident: 'Train withdrawal',
    kind: 'TRAIN_WITHDRAWAL',
    objective: 'Withdraw a live timetable train from mainline service to RT depot without stopping other services.',
    target: 'Mainline train to RT depot endpoint',
    title: 'Train Withdrawal',
    tasks: [
      {
        id: 'select-withdrawal-train',
        label: 'Select train to withdraw',
        mappedTaskId: 'selectTrain',
        monitor: 'Monitor 03 Timetable',
        weight: 10,
      },
      {
        critical: true,
        evidenceKeywords: ['route'],
        id: 'set-withdrawal-route',
        label: 'Set route to last station hold path',
        mappedTaskId: 'setRoute',
        monitor: 'Line Map',
        runtimeOnly: true,
        weight: 15,
      },
      {
        critical: true,
        evidenceKeywords: ['arrival time', 'skg', 'skgs', 'destination'],
        id: 'declare-last-station-destination',
        label: 'Declare SKG / SKGS destination in Arrival Time',
        monitor: 'Line Map Train Control',
        runtimeOnly: true,
        weight: 15,
      },
      {
        critical: true,
        evidenceKeywords: ['departure time', 's608', 'last station'],
        id: 'move-to-s608-hold',
        label: 'Apply Departure Time to move to S608 hold',
        monitor: 'Line Map Train Control',
        runtimeOnly: true,
        weight: 15,
      },
      {
        critical: true,
        evidenceKeywords: ['arrival time', 'ned', 'rt2d', 'destination'],
        id: 'declare-depot-destination',
        label: 'Declare NED / RT2D depot destination in Arrival Time',
        monitor: 'Line Map Train Control',
        runtimeOnly: true,
        weight: 15,
      },
      {
        critical: true,
        evidenceKeywords: ['departure time', 'depot', 'depart'],
        id: 'trigger-withdrawal-movement',
        label: 'Apply Departure Time to move to RT2 depot',
        mappedTaskId: 'dispatchTrain',
        monitor: 'Line Map Train Control',
        runtimeOnly: true,
        weight: 15,
      },
      {
        evidenceKeywords: ['depot endpoint', 'reached depot', 'endpoint'],
        id: 'verify-depot-endpoint',
        label: 'Verify train reaches depot endpoint',
        monitor: 'Line Map',
        runtimeOnly: true,
        weight: 10,
      },
      {
        id: 'review-withdrawal-outcome',
        label: 'Review final withdrawal state',
        mappedTaskId: 'completeScenario',
        monitor: 'IOS',
        weight: 5,
      },
    ],
  },
  {
    defaultTargetTrainId: '317',
    duration: '05:00',
    id: 'door-fault',
    incident: 'Door fault',
    kind: 'DOOR_FAULT',
    objective: 'Handle train door failure using alarm acknowledgement and controlled train commands.',
    target: 'Faulted train on mainline',
    title: 'Train Door Fault',
    tasks: [
      {
        id: 'select-door-fault-train',
        label: 'Select affected train',
        mappedTaskId: 'selectTrain',
        monitor: 'Monitor 02 Line Map',
        weight: 15,
      },
      {
        critical: true,
        id: 'acknowledge-door-fault',
        label: 'Acknowledge door fault alarm',
        mappedTaskId: 'ackAlarm',
        monitor: 'Alarms',
        weight: 25,
      },
      {
        critical: true,
        evidenceKeywords: ['closed/locked', 'isolate'],
        id: 'apply-door-procedure',
        label: 'Apply door fault procedure',
        monitor: 'Line Map Train Control',
        weight: 30,
      },
      {
        id: 'route-after-door-fault',
        label: 'Apply movement route after recovery',
        mappedTaskId: 'setRoute',
        monitor: 'Line Map',
        weight: 15,
      },
      {
        id: 'review-door-fault-outcome',
        label: 'Review final door fault state',
        mappedTaskId: 'completeScenario',
        monitor: 'IOS',
        weight: 15,
      },
    ],
  },
] as const

const scenarioDefinitionById = new Map(trainingScenarioDefinitions.map((definition) => [definition.id, definition]))

export const launchRoutePathIds = new Set([
  'timetable-skg-to-pgl-upper-mainline',
  'timetable-skg-to-pgc-upper-mainline',
])

export const trainingScenarioWorkflowDefinitions: Record<TrainingScenarioWorkflowAction, TrainingScenarioWorkflowDefinition> = {
  PREPARE_LAUNCH_ROUTE: {
    kind: 'TRAIN_LAUNCH',
    lineMapAction: 'PREPARE_LAUNCH_ROUTE',
    message: 'Launch route R655_617 prepared from RT1/S655 into SKG mainline.',
    taskIds: ['select-launch-train', 'set-launch-route'],
    value: 'LAUNCH ROUTE',
  },
  DISPATCH_LAUNCH: {
    kind: 'TRAIN_LAUNCH',
    lineMapAction: 'DISPATCH_LAUNCH',
    message: 'Launch train dispatched into timetable mainline service.',
    taskIds: ['dispatch-launch-train'],
    value: 'LAUNCH DISPATCH',
  },
  VERIFY_LAUNCH_MAINLINE: {
    kind: 'TRAIN_LAUNCH',
    lineMapAction: 'VERIFY_LAUNCH_MAINLINE',
    message: 'Launch train verified on SKG mainline service. Scenario complete.',
    taskIds: ['review-launch-outcome'],
    value: 'LAUNCH COMPLETE',
  },
  DECLARE_WITHDRAWAL_DESTINATION: {
    kind: 'TRAIN_WITHDRAWAL',
    lineMapAction: 'DECLARE_WITHDRAWAL_DESTINATION',
    message: 'Withdrawal destination declared in Arrival Time.',
    taskIds: ['declare-last-station-destination', 'declare-depot-destination'],
    value: 'WITHDRAW DEST',
  },
  TRIGGER_WITHDRAWAL_MOVEMENT: {
    kind: 'TRAIN_WITHDRAWAL',
    lineMapAction: 'TRIGGER_WITHDRAWAL_MOVEMENT',
    message: 'Withdrawal departure time applied and movement triggered.',
    taskIds: ['move-to-s608-hold', 'trigger-withdrawal-movement'],
    value: 'WITHDRAW DEPART',
  },
  VERIFY_WITHDRAWAL_ENDPOINT: {
    kind: 'TRAIN_WITHDRAWAL',
    lineMapAction: 'VERIFY_WITHDRAWAL_ENDPOINT',
    message: 'Withdrawal train verified at depot endpoint. Scenario complete.',
    taskIds: ['verify-depot-endpoint', 'review-withdrawal-outcome'],
    value: 'DEPOT ENDPOINT',
  },
  INJECT_DOOR_FAULT: {
    kind: 'DOOR_FAULT',
    lineMapAction: 'INJECT_DOOR_FAULT',
    message: 'Door fault injected on Train 317 and train held for operator response.',
    summaryTone: 'red',
    taskIds: ['select-door-fault-train'],
    tone: 'red',
    value: 'YES',
  },
  ACKNOWLEDGE_DOOR_FAULT: {
    kind: 'DOOR_FAULT',
    lineMapAction: 'ACKNOWLEDGE_DOOR_FAULT',
    message: 'Door fault alarm acknowledged for Train 317.',
    taskIds: ['acknowledge-door-fault'],
    value: 'ACK',
  },
  APPLY_DOOR_FAULT_PROCEDURE: {
    kind: 'DOOR_FAULT',
    lineMapAction: 'APPLY_DOOR_FAULT_PROCEDURE',
    message: 'Door procedure applied: Cycle Door and Confirm Closed/Locked completed.',
    taskIds: ['apply-door-procedure'],
    value: 'CLOSED/LOCKED',
  },
  AUTHORISE_DOOR_FAULT_RECOVERY: {
    kind: 'DOOR_FAULT',
    lineMapAction: 'AUTHORISE_DOOR_FAULT_RECOVERY',
    message: 'Door fault recovery movement authorised after route protection.',
    scenarioTaskIds: ['dispatchTrain'],
    taskIds: ['route-after-door-fault'],
    value: 'AUTHORISED TO MOVE',
  },
  COMPLETE_DOOR_FAULT_REVIEW: {
    kind: 'DOOR_FAULT',
    lineMapAction: 'COMPLETE_DOOR_FAULT_REVIEW',
    message: 'Door fault scenario review completed. Scenario complete.',
    taskIds: ['review-door-fault-outcome'],
    value: 'DOOR FAULT COMPLETE',
  },
}

export function getTrainingScenarioDefinition(id: string | undefined) {
  return scenarioDefinitionById.get(id ?? '') ?? idleTrainingScenarioDefinition
}
