from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path
from typing import Any

import openpyxl

from extract_nel_timetable import (
    SCHEDULE_RE,
    SERVICE_RE,
    TIME_RE,
    clean_cell,
    get_compact_services,
    get_notes,
    get_station_code,
    infer_event_kinds,
)


# The OTES "Full List" workbook repeats one block per timetable page:
#   Northbound/Southbound, blank, Service No., Schedule No., notes, station rows.
DIRECTION_LABELS = {"Northbound": "NB", "Southbound": "SB"}


def format_time_cell(value: Any) -> str:
    if isinstance(value, dt.time):
        return f"{value.hour}:{value.minute:02d}:{value.second:02d}"

    if isinstance(value, dt.timedelta):
        # After-midnight trips are stored as durations, e.g. 24:35:30.
        total = int(value.total_seconds())
        hour, remainder = divmod(total, 3600)
        minute, second = divmod(remainder, 60)
        return f"{hour}:{minute:02d}:{second:02d}"

    if isinstance(value, dt.datetime):
        return f"{value.hour}:{value.minute:02d}:{value.second:02d}"

    match = TIME_RE.search(clean_cell(value))

    if not match:
        return ""

    hour, minute, second = match.group(0).split(":")
    return f"{int(hour)}:{minute}:{second}"


def extract_timetable(xlsx_path: Path, title: str, effective_from: str) -> dict[str, Any]:
    workbook = openpyxl.load_workbook(str(xlsx_path), read_only=True, data_only=True)
    sheet = workbook.worksheets[0]
    rows = [list(row) for row in sheet.iter_rows(values_only=True)]
    services: list[dict[str, Any]] = []
    direction = ""
    block_number = 0

    for row_index, row in enumerate(rows):
        label = clean_cell(row[0] if row else "")

        if label in DIRECTION_LABELS:
            direction = DIRECTION_LABELS[label]
            continue

        if label != "Service No." or not direction:
            continue

        block_number += 1
        service_row = [clean_cell(cell) for cell in row]
        schedule_row = [clean_cell(cell) for cell in rows[row_index + 1]]
        note_row = [clean_cell(cell) for cell in rows[row_index + 2]]
        station_rows = []

        for station_row in rows[row_index + 3:]:
            station = get_station_code(clean_cell(station_row[0] if station_row else ""))

            if not station:
                break

            station_rows.append((station, station_row))

        for column_index, service_no in enumerate(service_row[1:], start=1):
            if not SERVICE_RE.fullmatch(service_no):
                continue

            schedule_no = schedule_row[column_index] if column_index < len(schedule_row) else ""

            if not SCHEDULE_RE.fullmatch(schedule_no):
                continue

            events: list[dict[str, Any]] = []

            for station_index, (station, station_row) in enumerate(station_rows, start=1):
                time = format_time_cell(station_row[column_index] if column_index < len(station_row) else None)

                if time:
                    events.append({"station": station, "time": time, "rowIndex": station_index})

            services.append({
                "direction": direction,
                "events": infer_event_kinds(events),
                "notes": get_notes(note_row[column_index] if column_index < len(note_row) else ""),
                "page": block_number,
                "scheduleNo": schedule_no,
                "serviceNo": service_no,
            })

    return {
        "source": {
            "file": str(xlsx_path),
            "title": title,
            "effectiveFrom": effective_from,
        },
        "services": services,
        "summary": {
            "serviceColumns": len(services),
            "uniqueScheduleNumbers": len({service["scheduleNo"] for service in services}),
            "uniqueServiceNumbers": len({service["serviceNo"] for service in services}),
        },
    }


def write_compact_ts(data: dict[str, Any], output: Path, selected_station: str, export_name: str) -> None:
    compact_services = get_compact_services(data, selected_station)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join([
            "import type { NelTimetableService } from './nelOtesWeekday03Services'",
            "",
            f"// Generated by scripts/extract_nel_timetable_xlsx.py from {data['source']['title']}",
            f"// (effective {data['source']['effectiveFrom']}). Do not edit by hand.",
            f"export const {export_name} = (",
            json.dumps(compact_services, indent=2),
            ") as const satisfies readonly NelTimetableService[]",
            "",
        ]),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract an NEL OTES 'Full List' timetable workbook.")
    parser.add_argument("xlsx", type=Path, help="Path to the NEL_OTES_Weekday_XX Full List workbook")
    parser.add_argument("--title", default="NEL_OTES_Weekday_04")
    parser.add_argument("--effective-from", default="2026-01-05")
    parser.add_argument("--output", type=Path, default=Path("tmp/timetable/nel_otes_weekday_04.json"))
    parser.add_argument("--compact-ts-output", type=Path)
    parser.add_argument("--export-name", default="nelOtesWeekday04Services")
    parser.add_argument("--selected-station", default="SKG")
    args = parser.parse_args()

    data = extract_timetable(args.xlsx, args.title, args.effective_from)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(data, indent=2), encoding="utf-8")
    if args.compact_ts_output:
        write_compact_ts(data, args.compact_ts_output, args.selected_station, args.export_name)
    print(json.dumps(data["summary"], indent=2))
    print(f"wrote {args.output}")
    if args.compact_ts_output:
        print(f"wrote {args.compact_ts_output}")


if __name__ == "__main__":
    main()
